#pragma once
#define LATTICEDB_VERSION_MAJOR 2
#define LATTICEDB_VERSION_MINOR 0
#define LATTICEDB_VERSION_PATCH 0
#define LATTICEDB_BUILD_TYPE "Release"
#define LATTICEDB_COMPILER "GNU"
#define LATTICEDB_CXX_STANDARD 17
