apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus.latticedb.monitoring:9090
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: GET

  - name: CloudWatch
    type: cloudwatch
    jsonData:
      authType: credentials
      defaultRegion: us-west-2
      customMetricsNamespaces: 'AWS/ECS,AWS/ApplicationELB,AWS/EFS'
    editable: true